version: '3'

name: go-test

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: "localdb"
      MYSQL_USER: "localuser"
      MYSQL_PASSWORD: "localpass"
